-- Migration 006: Create requests table
create table if not exists public.requests (
  id bigint generated by default as identity primary key,
  profile_id uuid references public.profiles(id) on delete cascade,
  title text,
  status text not null default 'received',
  requester jsonb,
  materials jsonb,
  pricing jsonb,
  created_at timestamptz not null default now()
);

alter table public.requests enable row level security;

create policy allow_requests_select on public.requests
  for select to anon, authenticated using (true);

create policy allow_requests_insert on public.requests
  for insert to anon, authenticated with check (true);

create policy allow_requests_update on public.requests
  for update to anon, authenticated using (true) with check (true);

grant insert, select, update on public.requests to anon, authenticated;
