-- Migration 007: Create negotiation_messages table
create table if not exists public.negotiation_messages (
  id bigint generated by default as identity primary key,
  negotiation_id bigint references public.negotiations(id) on delete cascade,
  sender_profile_id uuid references public.profiles(id),
  content text not null,
  created_at timestamptz not null default now()
);

alter table public.negotiation_messages enable row level security;

create policy allow_neg_messages_select on public.negotiation_messages
  for select to anon, authenticated using (true);

create policy allow_neg_messages_insert on public.negotiation_messages
  for insert to anon, authenticated with check (true);

grant insert, select on public.negotiation_messages to anon, authenticated;
